version: 2.1

job_defaults: &job_defaults
  working_directory: /go/src/github.com/jimmidyson/configmap-reload

  docker:
  - image: golang:1.14-alpine

  environment:
    CGO_ENABLED: "0"
    GO111MODULE: "on"

docker_job_defaults: &docker_job_defaults
  working_directory: /go/src/github.com/jimmidyson/configmap-reload

  docker:
  - image: jimmidyson/docker-with-buildx:stable-git

  environment:
    CGO_ENABLED: "0"
    GO111MODULE: "on"
    DOCKER_CLI_EXPERIMENTAL: "enabled"

jobs:
  checkout_code:
    <<: *job_defaults

    steps:
      - checkout

      - save_cache:
          key: code-repo-{{ .Environment.CIRCLE_SHA1 }}-{{ .Environment.CIRCLE_TAG }}
          paths:
          - /go/src/github.com/jimmidyson/configmap-reload

  build_docker_buildx:
    <<: *docker_job_defaults

    docker:
      - image: docker:stable-git

    steps:
      
      - restore_cache:
          keys:
          - code-repo-{{ .Environment.CIRCLE_SHA1 }}-{{ .Environment.CIRCLE_TAG }}
      
      - setup_remote_docker:
          version: 19.03.8
      
      - run:
          name: Build and push Docker buildx image
          command: |
            if [ "${CIRCLE_PROJECT_USERNAME}" != "jimmidyson" ]; then
              echo "Skipping - this is not in origin repository"
              exit 0
            fi
            if [ -z "${DOCKER_LOGIN}" ] || [ -z "${DOCKER_PASSWORD}" ]; then
              echo "Missing Docker login information!!!"
              exit 1
            fi
            docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}
            docker build -t jimmidyson/docker-with-buildx:stable-git -f Dockerfile.buildx .
            docker push jimmidyson/docker-with-buildx:stable-git

  build_docker:
    <<: *docker_job_defaults

    steps:
      - restore_cache:
          keys:
          - code-repo-{{ .Environment.CIRCLE_SHA1 }}-{{ .Environment.CIRCLE_TAG }}

      - setup_remote_docker:
          version: 19.03.8

      - run:
          name: Build multiarch Docker images
          command: |
            if [ "${CIRCLE_PROJECT_USERNAME}" != "jimmidyson" ]; then
              echo "Skipping - this is not in origin repository"
              exit 0
            fi
            DOCKER_TAG=${CIRCLE_TAG:-latest}
            apk add -U make bash
            make docker-build

  push_docker:
    <<: *docker_job_defaults

    steps:
      - restore_cache:
          keys:
          - code-repo-{{ .Environment.CIRCLE_SHA1 }}-{{ .Environment.CIRCLE_TAG }}

      - setup_remote_docker:
          version: 19.03.8

      - run:
          name: Push multiarch Docker images
          command: |
            if [ "${CIRCLE_PROJECT_USERNAME}" != "jimmidyson" ]; then
              echo "Skipping - this is not in origin repository"
              exit 0
            fi
            if [ -z "${DOCKER_LOGIN}" ] || [ -z "${DOCKER_PASSWORD}" ]; then
              echo "Missing Docker login information!!!"
              exit 1
            fi
            DOCKER_TAG=${CIRCLE_TAG:-latest}
            docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}
            apk add -U make bash
            make docker-push

workflows:
  version: 2
  build_and_deploy:
    jobs:
    - checkout_code:
        filters:
          tags:
            only:
              /v[0-9]+(\.[0-9]+)*/
    - build_docker_buildx:
        requires:
        - checkout_code
        filters:
          tags:
            only:
              /v[0-9]+(\.[0-9]+)*/
    - build_docker:
        requires:
        - build_docker_buildx
        filters:
          tags:
            only:
              /v[0-9]+(\.[0-9]+)*/
    - push_docker:
        requires:
        - build_docker_buildx
        filters:
          branches:
            only: master
          tags:
            only:
              /v[0-9]+(\.[0-9]+)*/
